#!/bin/bash

chromium 'https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&client_id=7lr08ttbgx9h7po1fhs4vr8xqpib6e&redirect_uri=http://localhost:8000&scope=viewing_activity_read&state=teststate&force_verify=true'
